### ISSUE TITLE
failed to build with mingw-w64-x86_64-clang

### ISSUE THREAD

**Issue by jonirrings** [bcmyers/argonautica#14]
hello, it seems failed to build with mingw on Windows, and it reports
```
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at C:\\msys64\\mingw64\\bin\\libclang.dll could not be opened:
```
the clang version is 8.0.1 from mingw, does it require specific clang version and msvc?

I'm trying to follow [this post](https://gill.net.in/posts/auth-microservice-rust-actix-web1.0-diesel-complete-tutorial/) and to build [his repo](https://gitlab.com/mygnu/rust-auth-server).

thanks

**Comment by frederikhors** [comment]
@jonirrings any news on this?

**Comment by jonirrings** [comment]
@frederikhors not yet

**Comment by frederikhors** [comment]
@jonirrings install from here: https://releases.llvm.org/download.html and it works.

**Comment by jonirrings** [comment]
@frederikhors thx
